#!/usr/bin/env node
// Pre-tool-use guard: block writes to auto-generated and secret files.
// Reads tool-call JSON on stdin, exits 2 to block the call.
import { readFileSync } from "node:fs";

let payload;
try {
  payload = JSON.parse(readFileSync(0, "utf8"));
} catch {
  process.exit(0);
}

const tool = payload?.tool_name ?? "";
const input = payload?.tool_input ?? {};
const target = String(input.file_path ?? input.notebook_path ?? "")
  .replace(/\\/g, "/")
  .toLowerCase();

if (!target) process.exit(0);

const rules = [
  {
    test: /\/lib\/generated\/prisma\//,
    msg: "Refusing to modify lib/generated/prisma/* — these files are auto-generated by `prisma generate` (.rules §8).",
  },
  {
    test: /(^|\/)\.env(\.local|\.production|\.development|\.test)?$/,
    msg: "Refusing to write .env files — secrets must never be committed (.rules §7).",
  },
];

for (const rule of rules) {
  if (rule.test.test(target)) {
    process.stderr.write(`[hook block] ${rule.msg}\n  path: ${target}\n  tool: ${tool}\n`);
    process.exit(2);
  }
}

if (/\/prisma\/schema\.prisma$/.test(target)) {
  process.stderr.write(
    "[hook warn] Editing prisma/schema.prisma — confirm field-level changes with the user before continuing (.rules §8).\n",
  );
}

process.exit(0);
