// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as loadEnv } from "dotenv";
import { defineConfig } from "prisma/config";

loadEnv({ path: ".env.local" });
loadEnv();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prefer the pooled URL for CLI operations in this environment because the
    // direct Supabase host is not always reachable from local development.
    url: process.env["DATABASE_URL"] ?? process.env["DIRECT_URL"]!,
  },
});
