BEGIN;
SET LOCAL lock_timeout = '5s';
ALTER TABLE "SalesQuotation" ADD COLUMN IF NOT EXISTS "revision" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "quotationRevision" INTEGER;
COMMIT;
