ALTER TABLE public."LineRecipient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."UserLineRecipient" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."LineDailySummaryDispatch" ENABLE ROW LEVEL SECURITY;
